name: Auto Assign PRs
on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  assign-pr:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_assignee.yml@master
    secrets: inherit
    with:
      assignees: 'clouddrove-ci'
