name: tf-checks
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.4
    with:
      working_directory: './examples/basic/'
  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@1.2.4
    with:
      working_directory: './examples/complete/'
